services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: meuuser
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: zippyzap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .data/redis:/data
    command: redis-server --appendonly yes
    restart: always
    environment:
      - REDIS_PASSWORD=mysecretpassword
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
    name: myapp_redis_data
  mongo_data: